version: '3'
services:
  srv:
    image: testrail/apache:6.0
    container_name: testrailwebsite
    restart: unless-stopped
    depends_on:
    - db
    networks:
      - testrail
    ports:
      - "${HTTP_PORT:-8000}:80"
    volumes:
      - 'testrail_config:/var/www/testrail/config/'
      - 'testrail_opt:/opt/testrail'

  db:
    image: mysql:5.7
    container_name: testrailmysql
    restart: unless-stopped
    expose:
    - '3306'
    networks:
      - testrail
    volumes:
      - 'testrail_mysql:/var/lib/mysql'
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./testrail-dump--2020-01-30.sql:/opt/import.sql:ro
    environment:
      MYSQL_USER:     "${DB_USER:-testuser}"
      MYSQL_PASSWORD: "${DB_PWD:-Genix@123}"
      MYSQL_DATABASE: "${DB_NAME:-testrail}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PWD:-Genix@123}"

networks:
  testrail:
    driver: bridge

volumes:
  testrail_opt:
    driver: local
    driver_opts:
      type: none
      device: "$PWD/${OPT_PATH:-_opt}"
      o: bind

  testrail_mysql:
    driver: local
    driver_opts:
      type: none
      device: "$PWD/${MYSQL_PATH:-_mysql}"
      o: bind

  testrail_config:
    driver: local
    driver_opts:
      type: none
      device: "$PWD/${CONFIG_PATH:-_config}"
      o: bind
